# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Linux-Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: [ubuntu-latest]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - run: npm run release

    - run: zip --junk-paths build/ATTRIBUTION.linux.zip build/ATTRIBUTION.*.json

    - name: Get release
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Upload debian installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_name: fs-viewer-linux-${{ github.event.release.tag_name }}.deb
        asset_path: dist/fs-viewer_${{ github.event.release.tag_name }}_amd64.deb
        asset_content_type: application/octlet-stream

    - name: Upload RPM installer
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_name: fs-viewer-linux-${{ github.event.release.tag_name }}.rpm
        asset_path: dist/fs-viewer-${{ github.event.release.tag_name }}.x86_64.rpm
        asset_content_type: application/octlet-stream

    - name: Upload ASAR archive
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_name: fs-viewer-linux-${{ github.event.release.tag_name }}.app.asar
        asset_path: dist/linux-unpacked/resources/app.asar
        asset_content_type: application/octlet-stream

    - name: Upload attribution files
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.get_release.outputs.upload_url }}
        asset_name: fs-viewer-linux-attributions-${{ github.event.release.tag_name }}.zip
        asset_path: build/ATTRIBUTION.linux.zip
        asset_content_type: application/zip
